import type { Listing } from "./types";

/**
 * SAMPLE listings — placeholders so the site is fully functional.
 * Agency: replace with real listings (address, photos, beds/baths/parking,
 * price/method, description). Set `status` to "sold" and fill soldPrice/soldDate
 * to move a listing to the Sold page automatically.
 */
export const listings: Listing[] = [
  {
    slug: "12-rata-street-palmerston-north",
    title: "Sunny family home in a sought-after pocket",
    status: "for-sale",
    address: "12 Rata Street, Hokowhitu",
    suburb: "palmerston-north",
    beds: 4,
    baths: 2,
    parking: 2,
    priceDisplay: "Enquiries over $829,000",
    featured: true,
    description: [
      "Beautifully presented and move-in ready, this Hokowhitu home blends space, sun and location.",
      "Open-plan living flows to a north-facing deck and fully fenced backyard — perfect for family life and entertaining.",
    ],
    features: [
      "North-facing open-plan living",
      "Modern kitchen with scullery",
      "Master with ensuite and walk-in robe",
      "Double internal-access garage",
      "Zoned for sought-after schools",
    ],
    images: [],
  },
  {
    slug: "8-kowhai-lane-feilding",
    title: "Character charm meets modern comfort",
    status: "for-sale",
    address: "8 Kōwhai Lane, Feilding",
    suburb: "feilding",
    beds: 3,
    baths: 1,
    parking: 1,
    priceDisplay: "Deadline Sale (unless sold prior)",
    featured: true,
    description: [
      "A warm, characterful home within walking distance of Feilding's award-winning town centre.",
      "Polished floors, high studs and a sunny section make this an easy one to love.",
    ],
    features: [
      "Original character features",
      "Log burner and heat pump",
      "Established, private garden",
      "Walk to town and schools",
    ],
    images: [],
  },
  {
    slug: "24-gorge-road-ashhurst",
    title: "Room to breathe on the village edge",
    status: "under-offer",
    address: "24 Gorge Road, Ashhurst",
    suburb: "ashhurst",
    beds: 4,
    baths: 2,
    parking: 3,
    priceDisplay: "Enquiries over $895,000",
    featured: true,
    description: [
      "A generous home on a large section with space for the whole family, plus a workshop for the hobbyist.",
      "Enjoy village living with the Manawatū Gorge tracks on your doorstep.",
    ],
    features: [
      "Large 900m² section",
      "Separate workshop / shedding",
      "Two living areas",
      "Minutes to Te Āpiti tracks",
    ],
    images: [],
  },
  {
    slug: "56-kimbolton-road-manawatu",
    title: "Lifestyle living with rural outlook",
    status: "for-sale",
    address: "56 Kimbolton Road, Manawatū",
    suburb: "manawatu",
    beds: 4,
    baths: 2,
    parking: 4,
    priceDisplay: "By Negotiation",
    description: [
      "A quality lifestyle property on the outskirts of the Manawatū with paddocks, shedding and a stylish family home.",
      "The best of country living, only minutes from town.",
    ],
    features: [
      "Approx. 1.2ha of usable land",
      "Three-bay implement shed",
      "Modern open-plan home",
      "Stunning rural views",
    ],
    images: [],
  },
  // Recently sold (drives the /sold page)
  {
    slug: "3-victoria-avenue-palmerston-north",
    title: "Sold by Team Toner",
    status: "sold",
    address: "3 Victoria Avenue, West End",
    suburb: "palmerston-north",
    beds: 3,
    baths: 1,
    parking: 1,
    priceDisplay: "Sold",
    soldPrice: "$712,000",
    soldDate: "2026-06-18",
    description: ["A classic West End bungalow that attracted strong buyer interest and a great result for our vendors."],
    features: [],
    images: [],
  },
  {
    slug: "19-manchester-street-feilding",
    title: "Sold by Team Toner",
    status: "sold",
    address: "19 Manchester Street, Feilding",
    suburb: "feilding",
    beds: 4,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldPrice: "$845,000",
    soldDate: "2026-05-30",
    description: ["Multiple offers and a premium result for this well-presented family home."],
    features: [],
    images: [],
  },
  {
    slug: "7-cambridge-avenue-ashhurst",
    title: "Sold by Team Toner",
    status: "sold",
    address: "7 Cambridge Avenue, Ashhurst",
    suburb: "ashhurst",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldPrice: "$668,000",
    soldDate: "2026-05-12",
    description: ["Sold under the asking expectation after a targeted marketing campaign."],
    features: [],
    images: [],
  },
];
