import type { Listing } from "./types";

/*
 * Real Team Toner listings, sourced from their Arizto profile
 * (arizto.co.nz/our-people/profile — Agent 37780) on 2026-08-26.
 *
 * Current listings carry their full campaign description and gallery;
 * sold listings carry a short summary and cover photo. `soldDate` is the
 * campaign publish date (used only for ordering and the sitemap — Arizto
 * does not publish sale dates or prices).
 *
 * To update: re-run the scrape against the Arizto listings API, or edit by
 * hand — set `status` to "sold" to move a listing to the Sold page.
 */
export const listings: Listing[] = [
  // --- Current listings ---
  {
    slug: "1354-rangitikei-line-newbury",
    title: "Country Living - City Convenience - Five Acres",
    status: "for-sale",
    address: "1354 Rangitikei Line, Newbury",
    suburb: "manawatu",
    beds: 3,
    baths: 1,
    parking: 4,
    priceDisplay: "Enquiries Over $850,000",
    featured: true,
    description: [
      "Discover the freedom of lifestyle living without giving up the convenience of town. Set on 2.02 hectares (around 5 acres) on the corner of Rangitikei Line and Hansen Line, this well-established property offers space for the family, paddocks for the animals, excellent shedding and easy access to both Palmerston North and Feilding.",
      "Originally built in 1921, the spacious 150m² weatherboard home has enjoyed many practical upgrades over the years, including re-piling, ceiling and underfloor insulation, near new septic system and aluminium joinery, creating a comfortable home ready to enjoy.",
      "The large family-sized kitchen forms a natural hub for everyday living, open plan dining area and warmed by a substantial woodburner with heat-transfer system. From here, the home flows through to a generous separate living room with heat pump and plenty of space to relax.",
      "There are three double bedrooms, a spacious modern family bathroom, separate laundry and a useful sunroom/back porch. A large deck provides the perfect spot for summer entertaining, relaxing and taking in the rural outlook.",
      "Outside is where this property really comes into its own. The five acres are divided into five fenced and gated paddocks, ideal for stock or lifestyle pursuits, with a loading race adding further practicality.",
      "Shedding is impressive, with triple-car garaging and workshop, a separate boat shed/workshop, woodshed and shearing shed. Raised vegetable gardens, a glasshouse and chook house are already in place for those wanting to embrace the good life.",
      "Water is well catered for with two tanks providing approximately 40,000 litres of storage, plus bore water. Adding further peace of mind, the property also benefits from a septic system installed approximately two years ago.",
      "Best of all, you can enjoy lifestyle living while remaining within an easy commute of both Palmerston North and Feilding. Zoned for Newbury School.",
    ],
    features: [
      "2.02ha (approx. five acres) in five fenced paddocks",
      "Approx. 150m² weatherboard home, re-piled and insulated",
      "Triple-car garaging, boat shed, woodshed and shearing shed",
      "Approx. 40,000L tank storage plus bore water",
      "Zoned for Newbury School",
    ],
    images: [
      "/listings/1354-rangitikei-line-newbury-1.jpg",
      "/listings/1354-rangitikei-line-newbury-2.jpg",
      "/listings/1354-rangitikei-line-newbury-3.jpg",
      "/listings/1354-rangitikei-line-newbury-4.jpg",
      "/listings/1354-rangitikei-line-newbury-5.jpg",
      "/listings/1354-rangitikei-line-newbury-6.jpg",
    ],
  },
  {
    slug: "20-monckton-street-feilding",
    title: "A Hidden Family Gem - Space, Style & Surprises!",
    status: "for-sale",
    address: "20 Monckton Street, Feilding",
    suburb: "feilding",
    beds: 3,
    baths: 1,
    parking: 3,
    priceDisplay: "Enquiries Over $629,000",
    description: [
      "Tucked privately away from the street down its own driveway. Impressively updated, wonderfully spacious and set on a huge 1,240m² fully fenced section, this is a fantastic family home with space, privacy and plenty of surprises.",
      "Built in 1977 and offering approximately 150m² of floor area, the home welcomes you through a generous entrance foyer into an exceptionally spacious living room. There’s room here for the whole family to spread out, while a woodburner and heat-transfer system keep things warm and cosy through the cooler months.",
      "The living flows naturally through to a generous dining area and sleek, modern white kitchen – a stylish and practical hub for everyday family life. Excellent indoor-outdoor flow takes you straight onto the deck, while the kitchen overlooks the backyard, making it easy to keep an eye on children and pets while preparing dinner.",
      "There are three bedrooms, including a spacious main bedroom, while the beautifully updated family bathroom features a wall-hung vanity, tiled finishes, separate shower and bath. A separate toilet adds everyday convenience.",
      "Storage is plentiful, and even the laundry/mudroom has something extra to offer – it's large enough to incorporate an office or study area for those needing a work-from-home space.",
      "Step outside and the surprises continue.",
      "The expansive 1,240m² section is fenced, private and offers loads of room for children and pets to play. Entertain friends on the partially covered deck, enjoy the paved courtyard, or simply appreciate having a backyard with genuine space around you.",
      "And then there’s the huge 9m x 6m garage – a real standout for anyone wanting serious garaging, workshop space or room for the toys. Add the generous off-street parking area and this property delivers practicality in spades.",
      "Private, spacious and packed with features, 20 Monckton Street offers far more than you might expect from the street.",
    ],
    features: [
      "Private, fully fenced 1,240m² section",
      "Approx. 150m² of family living",
      "Woodburner with heat-transfer system",
      "Beautifully updated kitchen and tiled bathroom",
      "Huge 9m x 6m garage plus off-street parking",
    ],
    images: [
      "/listings/20-monckton-street-feilding-1.jpg",
      "/listings/20-monckton-street-feilding-2.jpg",
      "/listings/20-monckton-street-feilding-3.jpg",
      "/listings/20-monckton-street-feilding-4.jpg",
      "/listings/20-monckton-street-feilding-5.jpg",
      "/listings/20-monckton-street-feilding-6.jpg",
    ],
  },
  {
    slug: "71-ruapehu-drive-fitzherbert",
    title: "Expansive Views, Exceptional Quality",
    status: "for-sale",
    address: "71 Ruapehu Drive, Fitzherbert",
    suburb: "summerhill",
    beds: 3,
    baths: 2,
    parking: 2,
    priceDisplay: "Enquiries Over $810,000",
    featured: true,
    description: [
      "Built in 2010 and cherished by the same family since new, 71 Ruapehu Drive is a beautifully maintained brick home combining quality, comfort and an impressive, elevated outlook, with attention to detail evident throughout.",
      "Step through the entrance foyer into an impressive open plan living room. A 2.7-metre-high stud enhances the sense of space, while expansive double-glazed joinery captures panoramic views, an ever-changing backdrop to everyday living.",
      "Quality spacious entertainer’s kitchen, thoughtfully designed with excellent workspace and storage. It connects effortlessly with the dining and living areas, where a gas-flame feature fire adds warmth and ambience.",
      "Indoor-outdoor living is a real highlight. Doors open to the expansive decking and bullnose veranda – a wonderful place to entertain, relax or simply enjoy the outlook. Beautifully manicured landscaped grounds, established plantings, and a dedicated BBQ area complete the setting.",
      "The three bedrooms are all doubles with a luxury family bathroom. The main suite providing a private retreat complete with walk-in wardrobe, ensuite, tiled shower, underfloor heating and direct access to the deck.",
      "A heat pump provides additional year-round comfort, complemented by near-new carpet, quality drapes and shade blinds.",
      "Practicality is equally well covered with excellent storage, internal-access double garaging, laundry area and a completely lined and painted loft room.",
      "Immaculately maintained, beautifully presented and clearly loved, 71 Ruapehu Drive brings together quality construction, thoughtful design, superb outdoor living and a wonderful, elevated outlook.",
      "Located in sort after Summerhill, 5minutes drive to city, with Summerhill shops close by, wonderful walkways, Massey University and zoned for sort after education.",
      "A home built to be enjoyed, with a view you’ll never tire of.",
    ],
    features: [
      "Built 2010 — brick, double glazed throughout",
      "2.7m stud and panoramic elevated views",
      "Master suite with walk-in robe, ensuite and underfloor heating",
      "Gas-flame feature fire plus heat pump",
      "Internal-access double garage with lined loft room",
    ],
    images: [
      "/listings/71-ruapehu-drive-fitzherbert-1.jpg",
      "/listings/71-ruapehu-drive-fitzherbert-2.jpg",
      "/listings/71-ruapehu-drive-fitzherbert-3.jpg",
      "/listings/71-ruapehu-drive-fitzherbert-4.jpg",
      "/listings/71-ruapehu-drive-fitzherbert-5.jpg",
      "/listings/71-ruapehu-drive-fitzherbert-6.jpg",
    ],
  },
  {
    slug: "30-monarch-drive-ashhurst",
    title: "BUILT 2020-Rural Views & Family Living",
    status: "for-sale",
    address: "30 Monarch Drive, Ashhurst",
    suburb: "ashhurst",
    beds: 4,
    baths: 2,
    parking: 2,
    priceDisplay: "Enquiries Over $779,000",
    featured: true,
    description: [
      "Positioned at the end of a peaceful cul-de-sac and bordering a reserve, this beautifully presented home offers the perfect blend of modern comfort and low-maintenance living. This stunning home is only six years old and has been thoughtfully designed to maximise sunshine, space, and picturesque rural views.",
      "Step inside and you’ll immediately appreciate the light-filled open-plan living, where oversized stacker doors create seamless indoor-outdoor flow, making it easy to entertain while keeping an eye on the kids playing safely in the fully fenced garden.",
      "At the heart of the home is a striking kitchen featuring a huge stone island bench offering plenty of workspace for family meals and entertaining guests. Room for generous dining and family living, a peaceful lounge area overlooking farmland is the perfect spot to relax inside, while the covered pergola outdoor living gives versatility all year round.",
      "If you’re searching for a modern family home without the stress and expense of a new build, this home delivers it all.",
      "Located in a quiet, family-friendly setting next to a reserve and just 15 minutes from Palmerston North, you’ll enjoy the charm of Ashhurst’s welcoming village community while still having the city within easy reach.",
      "Modern, stylish and beautifully positioned—this is one you won’t want to miss.",
    ],
    features: [
      "Built in 2020 by Supreme Homes, Linear weatherboard exterior",
      "Double glazed throughout for year-round comfort",
      "176m² (approx.) floor area on a well-fenced 665m² section",
      "Sun-filled open plan living with exceptional indoor-outdoor flow",
      "Stylish kitchen with stone island bench, double oven and steam oven",
      "Heat pump for efficient heating and cooling",
      "Four bedrooms including a spacious master with walk-in wardrobe and ensuite",
      "Well-appointed family bathroom, great storage",
      "Double internal access garage, garden shed",
      "Easy-care grounds with room for children and pets",
    ],
    images: [
      "/listings/30-monarch-drive-ashhurst-1.jpg",
      "/listings/30-monarch-drive-ashhurst-2.jpg",
      "/listings/30-monarch-drive-ashhurst-3.jpg",
      "/listings/30-monarch-drive-ashhurst-4.jpg",
      "/listings/30-monarch-drive-ashhurst-5.jpg",
      "/listings/30-monarch-drive-ashhurst-6.jpg",
    ],
  },
  {
    slug: "8-fountain-court-hokowhitu",
    title: "Grand Family Living with Timeless Elegance",
    status: "for-sale",
    address: "8 Fountain Court, Hokowhitu",
    suburb: "hokowhitu",
    beds: 5,
    baths: 3,
    parking: 2,
    priceDisplay: "By Negotiation",
    description: [
      "Positioned in one of Palmerston North's most desirable cul-de-sacs, this impressive 274m² residence offers exceptional space, timeless style and a thoughtfully designed floor plan for modern family living.",
      "Built in 1994, this five-bedroom, three-bathroom home boasts outstanding street appeal and multiple living areas. The formal lounge features both a woodburner and gas feature fireplace, while the separate dining room opens beautifully to the private rear garden.",
      "The expansive open-plan kitchen is designed for both everyday family living and effortless entertaining, offering extensive bench space, excellent storage and seamless flow to the spacious family living area and private rear courtyard. It's a space where family and friends will naturally come together.",
      "A downstairs bedroom and bathroom provide the perfect space for guests, extended family or those wanting single-level convenience. Upstairs you'll find four further bedrooms, a family bathroom, separate toilet with vanity, plus a generous master retreat complete with a walk-in wardrobe and ensuite.",
      "An HRV system ensures year-round comfort, while the lined attic above the double internal-access garage provides excellent additional storage. Double gates also allow convenient access to the rear yard.",
      "A rare opportunity to secure a substantial executive home in one of Palmerston North's most sought-after locations. Contact Team Toner today to arrange your private viewing or visit one of our open homes.",
    ],
    features: [
      "274m² executive home (built 1994)",
      "Five bedrooms, three bathrooms",
      "Formal lounge with woodburner & gas feature fireplace",
      "Separate dining opening to the rear garden",
      "Expansive kitchen with generous bench space & storage",
      "Spacious family living opening to a private courtyard",
      "Master suite with walk-in wardrobe & ensuite",
      "HRV ventilation system",
      "Lined attic storage room",
      "Double internal-access garage",
      "Double gates providing rear yard access",
    ],
    images: [
      "/listings/8-fountain-court-hokowhitu-1.jpg",
      "/listings/8-fountain-court-hokowhitu-2.jpg",
      "/listings/8-fountain-court-hokowhitu-3.jpg",
      "/listings/8-fountain-court-hokowhitu-4.jpg",
      "/listings/8-fountain-court-hokowhitu-5.jpg",
      "/listings/8-fountain-court-hokowhitu-6.jpg",
    ],
  },
  {
    slug: "58-bryant-street-takaro",
    title: "Character Charm with Modern Family Living",
    status: "for-sale",
    address: "58 Bryant Street, Takaro",
    suburb: "palmerston-north",
    beds: 4,
    baths: 2,
    parking: 1,
    priceDisplay: "Enquiries Over $670,000",
    description: [
      "Beautifully blending timeless 1927 character with modern updates, this spacious 155m² home sits on a generous 809m² section in a handy central location.",
      "The modern large kitchen is the central heart of the home, featuring a large island bench, excellent storage and a folding servery window opening to the expansive rear deck – perfect for effortless summer entertaining. Flowing from the kitchen is a versatile second living/media room or a potential fourth bedroom.",
      "The oversized master suite offers a walk-in wardrobe, modern ensuite and direct access to the rear deck. The remaining bedrooms are all generously sized with large double wardrobes.",
      "A separate front lounge with adjoining sunroom provides flexible space for a home office, nursery or reading room. Modern bathrooms, a heat pump, partial double glazing and gas infinity hot water add year-round comfort.",
      "Outside you'll find a large private backyard, single garage with lean-to, garden shed and plenty of room for families to enjoy.",
      "A wonderful blend of character, space and modern living in an excellent central location.",
      "Gas infinity hot water",
      "Single garage with attached lean-to and a Garden shed",
      "Excellent central location close to amenities.",
    ],
    features: [
      "1927 character with modern updates",
      "Approx. 155m² home on an 809m² section",
      "Island kitchen with servery window to the deck",
      "Oversized master with walk-in robe and ensuite",
      "Heat pump, partial double glazing and gas infinity hot water",
    ],
    images: [
      "/listings/58-bryant-street-takaro-1.jpg",
      "/listings/58-bryant-street-takaro-2.jpg",
      "/listings/58-bryant-street-takaro-3.jpg",
      "/listings/58-bryant-street-takaro-4.jpg",
      "/listings/58-bryant-street-takaro-5.jpg",
      "/listings/58-bryant-street-takaro-6.jpg",
    ],
  },
  {
    slug: "7-diamond-court-ashhurst",
    title: "A Home Youll Be Proud To Call Your Own",
    status: "for-sale",
    address: "7 Diamond Court, Ashhurst",
    suburb: "ashhurst",
    beds: 3,
    baths: 2,
    parking: 2,
    priceDisplay: "Enquiries Over $655,000",
    description: [
      "Tucked away in the bowl of this peaceful cul-de-sac this beautifully presented home offers the perfect blend of comfort, convenience, and low-maintenance living.",
      "Built in 2006 and meticulously maintained, this attractive three-bedroom home is ideal for families, retirees, or anyone seeking an easy-care lifestyle without compromising on space.",
      "Step inside and you’ll immediately appreciate the generous open-plan living area, perfectly positioned to capture all-day sunshine. The spacious open plan kitchen is the heart of the home, offering excellent bench space, ample storage, and effortless connection to the dining and living areas.",
      "One of the standout features is the exceptional indoor-outdoor flow. Ranchsliders open to a large covered entertaining deck complete with outdoor blinds, creating a fantastic second living area that can be enjoyed year-round. Whether you’re hosting family and friends or simply relaxing with a morning coffee, this space is sure to impress.",
      "The master bedroom enjoys its own ensuite and walk-in wardrobe, while two additional double bedrooms are serviced by a family bathroom, separate toilet, and separate laundry.",
      "Warm and welcoming through every season, the home features a cosy gas flame fire and gas infinity hot water for added comfort and efficiency.",
      "Outside, the beautifully landscaped 619m² section is easy-care and immaculately presented. There’s excellent off-street parking, room for a trailer, a separate double garage with workbench, large garden shed, and secure fencing for children and pets. Directly over the road is Whitten Reserve a perfect green space for the family and perhaps your little dog to enjoy.",
      "This is one of those homes that simply feels right the moment you arrive. A fantastic opportunity to secure a quality home in one of Ashhurst’s most desirable locations.",
    ],
    features: [
      "Built 2006 and meticulously maintained",
      "Covered entertaining deck with outdoor blinds",
      "Master with ensuite and walk-in wardrobe",
      "Gas flame fire and gas infinity hot water",
      "Landscaped 619m² section with separate double garage",
    ],
    images: [
      "/listings/7-diamond-court-ashhurst-1.jpg",
      "/listings/7-diamond-court-ashhurst-2.jpg",
      "/listings/7-diamond-court-ashhurst-3.jpg",
      "/listings/7-diamond-court-ashhurst-4.jpg",
      "/listings/7-diamond-court-ashhurst-5.jpg",
      "/listings/7-diamond-court-ashhurst-6.jpg",
    ],
  },
  {
    slug: "39-grove-road-ashhurst",
    title: "Views, Space & Lifestyle Opportunity",
    status: "for-sale",
    address: "39 Grove Road, Ashhurst",
    suburb: "ashhurst",
    beds: 0,
    baths: 0,
    parking: 0,
    priceDisplay: "Enquiries Over $395,000",
    description: [
      "If you’ve been searching for the perfect lifestyle section with stunning rural outlooks and the ideal place to build your dream home,",
      "39 Grove Road is a must-see.",
      "Set on a generous flat 6699m² section, this outstanding lifestyle block offers the perfect balance of space, privacy, and breathtaking surroundings. Accessed via a 6-metre wide driveway, the site opens out to an exceptional building platform where you’ll enjoy wonderful, elevated views stretching out to the ranges — the perfect backdrop for your future home.",
      "With power and fibre internet available at the boundary, much of the groundwork is already in place to help make your building journey easier and more convenient.",
      "The size and flat contour provide excellent flexibility for designing the lifestyle you’ve always wanted, with plenty of room for your dream home, sheds, landscaping, extra parking, and space for the kids or pets to enjoy.",
      "Positioned in a highly desirable rural location, this property offers peaceful country living while remaining conveniently handy to Ashhurst, Palmerston North, and the wider Feilding region.",
      "Lifestyle sections of this calibre, with views like these, are becoming increasingly difficult to secure.",
      "Start designing your future today and make your lifestyle dream a reality at 39 Grove Road.",
    ],
    features: [
      "Flat 6,699m² lifestyle section",
      "Exceptional building platform with rural outlooks",
      "6-metre wide driveway access",
      "Power and fibre available at the boundary",
    ],
    images: [
      "/listings/39-grove-road-ashhurst-1.jpg",
      "/listings/39-grove-road-ashhurst-2.jpg",
      "/listings/39-grove-road-ashhurst-3.jpg",
      "/listings/39-grove-road-ashhurst-4.jpg",
      "/listings/39-grove-road-ashhurst-5.jpg",
      "/listings/39-grove-road-ashhurst-6.jpg",
    ],
  },
  {
    slug: "11-grove-road-ashhurst",
    title: "Build Your Lifestyle on 1.01ha",
    status: "for-sale",
    address: "11 Grove Road, Ashhurst",
    suburb: "ashhurst",
    beds: 0,
    baths: 0,
    parking: 0,
    priceDisplay: "Enquiries Over $370,000",
    description: [
      "Open flat paddock, mature boundary planting and big-sky views set the tone for this 1.01ha lifestyle bare land holding in Ashhurst. Positioned at 11 Grove Road, it offers a simple, grounded opportunity for buyers wanting space around them while staying within easy reach of village and city convenience.",
      "The land has a practical, usable feel, with established fencing defining the paddock areas and wide-open grassed spaces giving you room to plan around your own needs. Whether you are thinking about a future home, animals, gardens or a more spacious everyday lifestyle, the setting gives you a strong starting point to work from, subject to the usual checks and consents.",
      "Mature trees and shelter planting add privacy, character and a sense of permanence, while the surrounding rural outlook keeps the property feeling calm and open. You have the freedom to consider a layout that makes the most of the sun, views and connection to the land.",
      "With power and fibre internet available at the boundary, much of the groundwork is already in place to help make your building journey easier and more convenient.",
      "Set in Ashhurst, the property keeps you close to the essentials while offering the breathing space lifestyle buyers are often searching for. Palmerston North is within easy reach, giving you access to wider services, schooling, shopping and employment while returning home to a quieter rural edge.",
      "For buyers looking to secure land and shape their next chapter from the ground up, this Grove Road lifestyle block is well worth a closer look. RV is $485,000",
    ],
    features: [
      "1.01ha flat bare-land lifestyle block",
      "Established fencing and mature shelter planting",
      "Power and fibre available at the boundary",
      "RV $485,000",
    ],
    images: [
      "/listings/11-grove-road-ashhurst-1.jpg",
      "/listings/11-grove-road-ashhurst-2.jpg",
      "/listings/11-grove-road-ashhurst-3.jpg",
      "/listings/11-grove-road-ashhurst-4.jpg",
      "/listings/11-grove-road-ashhurst-5.jpg",
      "/listings/11-grove-road-ashhurst-6.jpg",
    ],
  },

  // --- Sold (most recent first) ---
  {
    slug: "52-tennyson-avenue-kelvin-grove",
    title: "Brick Beauty with Bonus Parking!",
    status: "sold",
    address: "52 Tennyson Avenue, Kelvin Grove",
    suburb: "kelvin-grove",
    beds: 4,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-07-13",
    description: [
      "Beautifully presented brick home with outstanding street appeal in the bowl of a cul-de-sac. Built in 2006 and offering 228m² of thoughtfully designed living, this is a home where comfort, entertaining and family life come together effortlessly.",
      "Expansive open-plan kitchen, dining and family living area. Bathed in natural light, the spacious kitchen features generous bench space, a breakfast bar and plenty of storage.",
    ],
    features: [],
    images: [
      "/listings/52-tennyson-avenue-kelvin-grove-1.jpg",
    ],
  },
  {
    slug: "44-haydon-street-roslyn",
    title: "Huge Shedding/Garaging. Huge Potential.",
    status: "sold",
    address: "44 Haydon Street, Roslyn",
    suburb: "roslyn",
    beds: 4,
    baths: 1,
    parking: 4,
    priceDisplay: "Sold",
    soldDate: "2026-06-27",
    description: [
      "What an Opportunity This Property Offers!",
      "If you've been searching for a property where you can roll up your sleeves, add your own style, and reap the rewards, then 44 Haydon Street deserves your immediate attention.",
    ],
    features: [],
    images: [
      "/listings/44-haydon-street-roslyn-1.jpg",
    ],
  },
  {
    slug: "33-ruahine-street-roslyn",
    title: "Walk to Work – Hospital Convenience at Its Best!",
    status: "sold",
    address: "33 Ruahine Street, Roslyn",
    suburb: "roslyn",
    beds: 3,
    baths: 1,
    parking: 1,
    priceDisplay: "Sold",
    soldDate: "2026-06-12",
    description: [
      "Location doesn't get much more convenient than this! Situated almost directly opposite Palmerston North Hospital, this well-presented three-bedroom home offers an easy-care lifestyle that's perfect for hospital staff, healthcare professionals, first-home buyers, investors, or families wanting everyday convenience. Leave the car at home and enjoy the luxury of being able to walk to work, nearby amenities, schools, and public transport.",
      "Built in 1993 and set back from the road on a private, fully fenced 399m² section, this attractive home offers security, comfort, and low-maintenance living.",
    ],
    features: [],
    images: [
      "/listings/33-ruahine-street-roslyn-1.jpg",
    ],
  },
  {
    slug: "43-norfolk-crescent-feilding",
    title: "Private Established Setting. Unbeatable!",
    status: "sold",
    address: "43 Norfolk Crescent, Feilding",
    suburb: "feilding",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-05-27",
    description: [
      "Tucked away in a quiet cul-de-sac, 43 Norfolk Crescent offers easy, single-level living on a generous 966m2 private section - perfect for families, first home buyers or those wanting space, privacy and an amazing setting. Built in 1965 and offering 118m2 of floor area, this home delivers practical living in a relaxing setting full of birdlife. You’ll fall in love with this environment!",
      "The open plan living and dining area is light-filled and comfortable year round, with a gas fireplace, heat pump and Smartvent ventilation system. The kitchen is functional with good storage and outlook to the backyard. There is easy access to the rear covered deck which overlooks the garden. What a pleasure it will be entertaining here.",
    ],
    features: [],
    images: [
      "/listings/43-norfolk-crescent-feilding-1.jpg",
    ],
  },
  {
    slug: "26-wilson-crescent-highbury",
    title: "Corner Site with Smart Development Potential",
    status: "sold",
    address: "26 Wilson Crescent, Highbury",
    suburb: "palmerston-north",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-05-27",
    description: [
      "What truly sets this property apart is the outstanding corner-site development potential. With plenty of room and favourable positioning there is scope to explore subdivision, perhaps move on a transportable home (subject to Palmerston North City Council Approval).",
      "Or perhaps you want to build yourself a massive mancave? Opportunities like this are becoming increasingly rare.",
    ],
    features: [],
    images: [
      "/listings/26-wilson-crescent-highbury-1.jpg",
    ],
  },
  {
    slug: "36-gloucester-street-takaro",
    title: "Where Memories Begin - 976m2 Section",
    status: "sold",
    address: "36 Gloucester Street, Takaro",
    suburb: "palmerston-north",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-05-01",
    description: [
      "Tucked quietly in the bowl of a cul-de-sac, 36 Gloucester Street is the kind of home that tells a story—and invites you to write the next chapter.",
      "Lovingly held by the same family for an incredible 54 years, this warm and welcoming 1958-built home offers space, comfort, and a true sense of belonging. Set on a generous 976m² section, it’s the perfect match for families and first home buyers looking to secure their future in a peaceful, family-friendly setting.",
    ],
    features: [],
    images: [
      "/listings/36-gloucester-street-takaro-1.jpg",
    ],
  },
  {
    slug: "7a-wigan-place-hokowhitu",
    title: "Freehold, Private & Perfectly Positioned",
    status: "sold",
    address: "7A Wigan Place, Hokowhitu",
    suburb: "hokowhitu",
    beds: 2,
    baths: 1,
    parking: 1,
    priceDisplay: "Sold",
    soldDate: "2026-04-29",
    description: [
      "Tucked away in a quiet cul-de-sac in one of Hokowhitu’s most sought-after pockets, 7A Wigan Place offers the perfect blend of comfort, privacy, and low-maintenance living—all on its own freehold 690m² easy care and well fenced section.",
      "Solidly built in the 1970s with timeless brick construction, this well-maintained and updated 123m2 townhouse is ideal for downsizers, professionals, or those looking for a secure and easy-care lifestyle in a premium location. With Hokowhitu Park and Village shops just minutes’ walk away",
    ],
    features: [],
    images: [
      "/listings/7a-wigan-place-hokowhitu-1.jpg",
    ],
  },
  {
    slug: "105a-pahiatua-street-hokowhitu",
    title: "Lifestyle Living in Town! Private Setting!",
    status: "sold",
    address: "105A Pahiatua Street, Hokowhitu",
    suburb: "hokowhitu",
    beds: 4,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-04-15",
    description: [
      "Tucked quietly off the road on a beautifully established 1,194m² section, 105A Pahiatua Street is a truly special property—where timeless mid-century architecture [David Chappell] meets a peaceful, nature-filled lifestyle right in the heart of Hokowhitu.",
      "Surrounded by mature trees and alive with birdsong, this is a home that feels a world away, yet is just moments from the city, hospital, river walkway/cycle tracks, Hokowhitu Village, quality schooling and Massey University",
    ],
    features: [],
    images: [
      "/listings/105a-pahiatua-street-hokowhitu-1.jpg",
    ],
  },
  {
    slug: "371-tutaki-road-bunnythorpe",
    title: "DREAMING OF THE COUNTRY LIFESTYLE?",
    status: "sold",
    address: "371 Tutaki Road, Bunnythorpe",
    suburb: "manawatu",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-04-03",
    description: [
      "YOUR WAIT IS OVER- AN AFFORDABLE LIFESTYLE IN GREAT LOCATION, AND MOVE IN READY!",
      "Set on an elevated 2.15ha lifestyle block just a short 10-minute drive from the city, this exceptional property offers the perfect balance of rural tranquillity and everyday convenience—a combination seldom found in such a tightly held location.",
    ],
    features: [],
    images: [
      "/listings/371-tutaki-road-bunnythorpe-1.jpg",
    ],
  },
  {
    slug: "2828-state-highway-1-sanson",
    title: "Affordable Lifestyle with Real Potential",
    status: "sold",
    address: "2828 State Highway 1, Sanson",
    suburb: "manawatu",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-04-03",
    description: [
      "Affordable Lifestyle Living – Space, Potential & Position",
      "Set on just over an acre in a super convenient Sanson location, this character-filled home offers a fantastic opportunity for those looking to secure space, versatility, and value in today’s market.",
    ],
    features: [],
    images: [
      "/listings/2828-state-highway-1-sanson-1.jpg",
    ],
  },
  {
    slug: "5-sheffield-street-awapuni",
    title: "Family Living in a Location You'll Love",
    status: "sold",
    address: "5 Sheffield Street, Awapuni",
    suburb: "awapuni",
    beds: 4,
    baths: 1,
    parking: 1,
    priceDisplay: "Sold",
    soldDate: "2026-03-26",
    description: [
      "Positioned in ever-popular Awapuni, this spacious and welcoming home offers the perfect setting for growing families—where lifestyle, comfort, and convenience come together.",
      "With the river closeby, weekend bike rides and family walks will quickly become part of everyday life. Add to that the convenience of nearby Pitama shops and cafés, and you’ve got a location that truly ticks the boxes.",
    ],
    features: [],
    images: [
      "/listings/5-sheffield-street-awapuni-1.jpg",
    ],
  },
  {
    slug: "34-richmond-avenue-takaro",
    title: "FIRST HOME OPPORTUNITY",
    status: "sold",
    address: "34 Richmond Avenue, Takaro",
    suburb: "palmerston-north",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-03-26",
    description: [
      "Welcome to 34 Richmond Avenue, Takaro—a solid 1950s home offering space, comfort, and exciting potential for the future.",
      "Set on a generous 691m² section, this 111m² roughcast home is perfect for first home buyers, growing families, or those looking to add value. With a large backyard, there’s plenty of room for kids and pets to play—and even the potential to explore adding a granny flat or additional improvements (subject to council approval).",
    ],
    features: [],
    images: [
      "/listings/34-richmond-avenue-takaro-1.jpg",
    ],
  },
  {
    slug: "166-cambridge-avenue-ashhurst",
    title: "PRICE DROP – Owners Relocating & Want It SOLD!",
    status: "sold",
    address: "166 Cambridge Avenue, Ashhurst",
    suburb: "ashhurst",
    beds: 3,
    baths: 1,
    parking: 3,
    priceDisplay: "Sold",
    soldDate: "2026-03-25",
    description: [
      "Outstanding Value – Private, Modern & Move-In Ready",
      "If you’ve been searching for a home that offers exceptional value for money, comfort, and convenience, this is your opportunity to act.",
    ],
    features: [],
    images: [
      "/listings/166-cambridge-avenue-ashhurst-1.jpg",
    ],
  },
  {
    slug: "10-te-kahu-lane-halcombe",
    title: "Your lifestyle upgrade starts here!",
    status: "sold",
    address: "10 Te Kahu Lane, Halcombe",
    suburb: "manawatu",
    beds: 4,
    baths: 2,
    parking: 3,
    priceDisplay: "Sold",
    soldDate: "2026-03-22",
    description: [
      "Built in 2024, this striking contemporary residence delivers the ultimate in modern lifestyle living-where space, style, and sustainability come together in perfect harmony.",
      "Set on 5,135m² of landscaped grounds, enjoying sweeping rural views, the impressive 230m2 home sits within a sought-after enclave of quality lifestyle properties.",
    ],
    features: [],
    images: [
      "/listings/10-te-kahu-lane-halcombe-1.jpg",
    ],
  },
  {
    slug: "13-pearl-grove-ashhurst",
    title: "Pearl Grove Perfection!",
    status: "sold",
    address: "13 Pearl Grove, Ashhurst",
    suburb: "ashhurst",
    beds: 3,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-03-19",
    description: [
      "Welcome to a home that perfectly blends modern style, comfort, and effortless living. Built in 2019 by GJ Gardner Homes, this beautifully presented 157m² residence offers a turnkey lifestyle ideal for those looking to downsize without compromise. Equally fabulous for a growing family.",
      "Constructed with timeless brick and Linea weatherboard, and complemented by sleek black aluminium double glazing, this home delivers both durability and contemporary appeal.",
    ],
    features: [],
    images: [
      "/listings/13-pearl-grove-ashhurst-1.jpg",
    ],
  },
  {
    slug: "7-brodie-lane-feilding",
    title: "Great Address! Amazing Setting!",
    status: "sold",
    address: "7 Brodie Lane, Feilding",
    suburb: "feilding",
    beds: 4,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-03-09",
    description: [
      "Tucked away in a peaceful and highly sought-after setting, 7 Brodie Lane, Feilding is a truly special property that offers privacy, space, and an enchanting connection to nature.",
      "Set on an established 1180m² section, this is a gardener’s delight like no other. Wander through pathways framed by roses and mature plantings, enjoy an abundance of birdlife, and harvest fruit from your own trees. The grounds are beautifully established, private, and thoughtfully designed to create a sense of calm and escape.",
    ],
    features: [],
    images: [
      "/listings/7-brodie-lane-feilding-1.jpg",
    ],
  },
  {
    slug: "25-vernon-avenue-takaro",
    title: "Charming 1950s Cottage – An Affordable First Home",
    status: "sold",
    address: "25 Vernon Avenue, Takaro",
    suburb: "palmerston-north",
    beds: 3,
    baths: 1,
    parking: 1,
    priceDisplay: "Sold",
    soldDate: "2026-03-06",
    description: [
      "Built in 1958, this much-loved cottage is ready to welcome its next chapter. Full of heart, character, and comfort, this home has been thoughtfully maintained and offers an inviting opportunity for first-home buyers or perhaps older couples wanting to slow down and enjoy the garden.",
      "Set on a 426m² section in a quiet, family-friendly street, the home features 95m2 floor area. Inside, you’ll find three bedrooms, a sunny lounge that opens via ranch slider to a delightful courtyard, and a cute, old-style kitchen and dining area that reflects the charm of its era.",
    ],
    features: [],
    images: [
      "/listings/25-vernon-avenue-takaro-1.jpg",
    ],
  },
  {
    slug: "18-monarch-drive-ashhurst-ashhurst",
    title: "WHY BUILD? JUST MOVE IN !",
    status: "sold",
    address: "18 Monarch Drive, Ashhurst",
    suburb: "ashhurst",
    beds: 3,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-03-05",
    description: [
      "Built in 2020 and meticulously maintained, this 6 year young brick home by GJ Gardner Homes offers effortless modern living on a gorgeous corner site, surrounded by other quality, near-new homes in a quiet street.",
      "Step inside via the inviting entranceway to light-filled, spacious open-plan living, perfectly designed for everyday comfort. The home is double glazed, low maintenance, and kept cosy year-round with a heat pump. Stacker doors open seamlessly to a covered archgola outdoor dining area, delivering that all-important indoor–outdoor flow perfect for entertaining.",
    ],
    features: [],
    images: [
      "/listings/18-monarch-drive-ashhurst-ashhurst-1.jpg",
    ],
  },
  {
    slug: "175-amberley-avenue-highbury",
    title: "Renovated, Spacious & Packed With Value!",
    status: "sold",
    address: "175 Amberley Avenue, Highbury",
    suburb: "palmerston-north",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-02-26",
    description: [
      "If you’ve been searching for space, modern upgrades and genuine value for money — 175 Amberley Avenue delivers.",
      "This solid 1979 brick home sits proudly on a well-fenced 669m² corner site and offers a generous 170m² floor plan that feels light, fresh and move-in ready. The hard work has been done — simply move in and enjoy.",
    ],
    features: [],
    images: [
      "/listings/175-amberley-avenue-highbury-1.jpg",
    ],
  },
  {
    slug: "263-cambridge-avenue-ashhurst",
    title: "Classic Ashhurst Living with Space to Grow",
    status: "sold",
    address: "263 Cambridge Avenue, Ashhurst",
    suburb: "ashhurst",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-02-23",
    description: [
      "Positioned on a generous 809m² section in popular Ashhurst, this solid 1970s-built home offers the perfect combination of comfort, practicality, and future potential.",
      "Lovingly held by the same family since new, this well-maintained 111m² home is now ready for its next owners to move in and make it their own. Whether you're a first home buyer, family, investor, or simply searching for a home with great bones and excellent garaging, this property offers genuine value in today’s market.",
    ],
    features: [],
    images: [
      "/listings/263-cambridge-avenue-ashhurst-1.jpg",
    ],
  },
  {
    slug: "10-antrim-place-hokowhitu",
    title: "RENOVATED, 4BRM  PLUS RUMPUS, ACT FAST!",
    status: "sold",
    address: "10 Antrim Place, Hokowhitu",
    suburb: "hokowhitu",
    beds: 4,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-02-22",
    description: [
      "Welcome to 10 Antrim Place - A nicely renovated, modern 137m2 home on a 660m2 section in a quiet Hokowhitu cul-de-sac.",
      "Step inside to spacious living area complemented by a freestanding woodburner for cosy winter evenings, the modern open-plan kitchen and dining room is designed for practicality and connection, boasting expansive bench space, large oven and gas hob, and excellent storage. The sunny dining area flows seamlessly out to patio, creating an ideal space for entertaining and relaxed family living. Complemented by a heatpump for year-round comfort.",
    ],
    features: [],
    images: [
      "/listings/10-antrim-place-hokowhitu-1.jpg",
    ],
  },
  {
    slug: "27-balrickard-way-milson",
    title: "Modern, Spacious & Ready to Enjoy",
    status: "sold",
    address: "27 Balrickard Way, Milson",
    suburb: "milson",
    beds: 4,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-02-22",
    description: [
      "If you’ve been thinking about building, think again. Why build when you can simply move in, relax, and start entertaining? This impressive 2017-built, 223m² double-glazed home delivers scale, style, and serious functionality — offering far more than first meets the eye.",
      "At the heart of the home is a stunning open-plan kitchen, dining and living space designed for effortless entertaining. The kitchen makes a statement with quality finishes and flows seamlessly to a large covered patio, creating exceptional indoor/outdoor living for year-round gatherings. A walk-in butler’s pantry cleverly incorporates the laundry, keeping everything practical, tidy and beautifully organised.",
    ],
    features: [],
    images: [
      "/listings/27-balrickard-way-milson-1.jpg",
    ],
  },
  {
    slug: "202-botanical-road-takaro",
    title: "Unlock the Potential – Priced to Sell!",
    status: "sold",
    address: "202 Botanical Road, Takaro",
    suburb: "palmerston-north",
    beds: 3,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-02-19",
    description: [
      "If you’ve been waiting for an opportunity to add value and reap the rewards — this is it.",
      "Built in 1951 and offering 128m² of practical living space, 20 Botanical Road is packed with potential for buyers with a few DIY skills and a vision. The bones are here, the layout works, and the upside is real.",
    ],
    features: [],
    images: [
      "/listings/202-botanical-road-takaro-1.jpg",
    ],
  },
  {
    slug: "14-ferndale-place-feilding",
    title: "Sun-Soaked Living with Supersized Garage",
    status: "sold",
    address: "14 Ferndale Place, Feilding",
    suburb: "feilding",
    beds: 3,
    baths: 1,
    parking: 4,
    priceDisplay: "Sold",
    soldDate: "2026-02-18",
    description: [
      "Tucked away in a quiet cul-de-sac, this very well-presented 1983-built home offers comfort, space, and a serious bonus for those needing extra garaging.",
      "Set on a generous 692m² landscaped section, this 120m² home is ready for you to simply move in and enjoy.",
    ],
    features: [],
    images: [
      "/listings/14-ferndale-place-feilding-1.jpg",
    ],
  },
  {
    slug: "77-sedcole-street-pahiatua",
    title: "Classic Villa, Big Section & Huge Garage",
    status: "sold",
    address: "77 Sedcole Street, Pahiatua",
    suburb: "manawatu",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-02-11",
    description: [
      "Set on a generous 1012m² established section, this beautifully maintained 1910 character villa blends timeless charm with important modern upgrades—making it a standout family home in the heart of Pahiatua.",
      "The 132m² home has had the heavy lifting done, including rewiring, re-piling, and a new roof, giving peace of mind while preserving the villa’s original warmth and personality. Inside you’ll find three genuine bedrooms and a modern family bathroom featuring a shower-over-bath, vanity, and toilet. New carpet also!",
    ],
    features: [],
    images: [
      "/listings/77-sedcole-street-pahiatua-1.jpg",
    ],
  },
  {
    slug: "10-hollows-crescent-takaro",
    title: "Low-Maintenance, Renovated, Freehold, Affordable!",
    status: "sold",
    address: "10 Hollows Crescent, Takaro",
    suburb: "palmerston-north",
    beds: 2,
    baths: 1,
    parking: 1,
    priceDisplay: "Sold",
    soldDate: "2026-02-06",
    description: [
      "Positioned in a quiet location at 10 Hollows Crescent, Takaro, this modernised 88m² unit presents an excellent opportunity for first-home buyers, downsizers, or investors seeking comfort, value, and easy living.",
      "Built in 1973, the home has been thoughtfully renovated and is one of two units, joined only by garages, offering added privacy. It sits on its own freehold title on an easy-care 490m² section.",
    ],
    features: [],
    images: [
      "/listings/10-hollows-crescent-takaro-1.jpg",
    ],
  },
  {
    slug: "114a-stanford-street-ashhurst",
    title: "Price Slashed – Get in quick!!",
    status: "sold",
    address: "114A Stanford Street, Ashhurst",
    suburb: "ashhurst",
    beds: 3,
    baths: 2,
    parking: 0,
    priceDisplay: "Sold",
    soldDate: "2026-02-05",
    description: [
      "Welcome to 114A Stanford Street, Ashhurst – a sleek, modern home that blends contemporary style with everyday comfort.",
      "Built in 2017 this 97m² home makes an immediate impression with its striking black exterior and smart, easy-care design.",
    ],
    features: [],
    images: [
      "/listings/114a-stanford-street-ashhurst-1.jpg",
    ],
  },
  {
    slug: "7-hill-court-awapuni",
    title: "ACT FAST – Awapuni Value You Can’t Ignore!",
    status: "sold",
    address: "7 Hill Court, Awapuni",
    suburb: "awapuni",
    beds: 4,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-02-04",
    description: [
      "Set down a quiet lane off Pitama Road, 7 Hill Court delivers generous proportions, modern comfort, and a layout that works beautifully for family living, in a sort after area, at an amazing affordable price!",
      "At the heart of the home your family will love the massive feature kitchen with excellent bench space and a substantial oven with gas hob. Flowing seamlessly into the sunny open-plan dining area with easy indoor/outdoor connection to courtyard—perfect for everyday living and entertaining.",
    ],
    features: [],
    images: [
      "/listings/7-hill-court-awapuni-1.jpg",
    ],
  },
  {
    slug: "61-apollo-parade-milson",
    title: "Price Slashed – Serious Garaging, Serious Value!",
    status: "sold",
    address: "61 Apollo Parade, Milson",
    suburb: "milson",
    beds: 3,
    baths: 1,
    parking: 4,
    priceDisplay: "Sold",
    soldDate: "2026-01-28",
    description: [
      "Welcome to 61 Apollo Parade, Milson, a property that truly delivers where it matters most – space, storage, and smart living.",
      "Set on a generous 997m² section the property has fence and gates onto JFK Drive, this home is perfectly suited to tradespeople, contractors, or anyone needing serious room for vehicles, tools, trailers, or machinery.",
    ],
    features: [],
    images: [
      "/listings/61-apollo-parade-milson-1.jpg",
    ],
  },
  {
    slug: "11-leander-place-milson",
    title: "Modern Family Living with Space & Style",
    status: "sold",
    address: "11 Leander Place, Milson",
    suburb: "milson",
    beds: 4,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-01-12",
    description: [
      "Positioned in the ever-popular Milson suburb, 11 Leander Place is a beautifully presented, family-friendly home that delivers space, flexibility, and effortless modern living. Set on a generous 729m² section, this well-designed 192m² residence is one where you can simply move in, unpack, and enjoy.",
      "The heart of the home is the fabulous modern kitchen, perfectly anchoring the open-plan living and dining area — a welcoming hub for everyday family life and entertaining alike. A separate, generously sized lounge with a feature gas fireplace provides a second living zone, ideal for relaxed evenings or hosting guests. Both living areas flow seamlessly to sun-soaked decking, creating excellent indoor/outdoor connection and multiple spaces to entertain or unwind.",
    ],
    features: [],
    images: [
      "/listings/11-leander-place-milson-1.jpg",
    ],
  },
  {
    slug: "47-geneva-terrace-kelvin-grove",
    title: "Everything a Family Home Should Be",
    status: "sold",
    address: "47 Geneva Terrace, Kelvin Grove",
    suburb: "kelvin-grove",
    beds: 4,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-01-12",
    description: [
      "Some homes simply understand family life. The need for space, the value of light, and the importance of a layout that keeps everyone connected. This one delivers all of that and more, set on a 719sqm section in one of Kelvin Grove’s most dependable streets.",
      "From the street, it makes a confident first impression. Solid, well-presented and generous in scale, it sets the tone for what unfolds inside. Step through the door into wide open-plan living.",
    ],
    features: [],
    images: [
      "/listings/47-geneva-terrace-kelvin-grove-1.jpg",
    ],
  },
  {
    slug: "6-dundas-road-sanson",
    title: "Easy Living - Exceptional Extras + 2bed sleepout.",
    status: "sold",
    address: "6 Dundas Road, Sanson",
    suburb: "manawatu",
    beds: 5,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2026-01-11",
    description: [
      "Set on a generous quarter-acre (1,012m²) section, this charming 1948-built home at 6 Dundas Road, Sanson offers an exceptional blend of character, comfort, and flexibility — perfect for families, home-based professionals, or those simply craving space.",
      "The 139m² home features three large bedrooms, including a master with a wet-floor ensuite, providing both comfort and practicality. Adding to the home’s versatility is a separate two-roomed utility space — ideal as a work-from-home setup, creative studio, hobby rooms, or extra accommodation for extended family.",
    ],
    features: [],
    images: [
      "/listings/6-dundas-road-sanson-1.jpg",
    ],
  },
  {
    slug: "20-collingwood-street-hokowhitu",
    title: "Timeless Hokowhitu Charm - Act Quickly!",
    status: "sold",
    address: "20 Collingwood Street, Hokowhitu",
    suburb: "hokowhitu",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-12-17",
    description: [
      "Positioned in one of Hokowhitu’s most popular streets, 20 Collingwood Street delivers discerning buyers a classic 1950s home in a blue-chip location.",
      "Built in 1958, the 108m² weatherboard home sits on a delightful 501m² established setting, complete with mature trees, vibrant planting, and the daily soundtrack of birdsong. Peaceful, private, and perfectly placed, it’s just moments from river walkways and cycleways, the Esplanade, an easy walk to the CBD—your daily commute may officially become optional?",
    ],
    features: [],
    images: [
      "/listings/20-collingwood-street-hokowhitu-1.jpg",
    ],
  },
  {
    slug: "9-ongley-street-feilding",
    title: "Just move in and Enjoy - Immaculate!",
    status: "sold",
    address: "9 Ongley Street, Feilding",
    suburb: "feilding",
    beds: 2,
    baths: 1,
    parking: 1,
    priceDisplay: "Sold",
    soldDate: "2025-12-08",
    description: [
      "In a marketplace where buyers are spoiled for choice, this one stands out for all the right reasons. Delivering serious value, contemporary comfort, and undeniable charm, this upgraded 1975-built gem positions you for a seamless move-in and an easy-care lifestyle.",
      "Step inside this light-filled 74m² two-bedroom home and you’ll quickly see why it punches above its weight. With a full internal and external repaint, rewiring, and a brand-new roof in 2024, the heavy lifting has already been done. Add in gas infinity hot water, a modernised kitchen, bathroom, and laundry, and you’ve got a future-proofed home that’s ready to perform from day one.",
    ],
    features: [],
    images: [
      "/listings/9-ongley-street-feilding-1.jpg",
    ],
  },
  {
    slug: "440-ruahine-street-terrace-end",
    title: "Family Home in Top School Zones!",
    status: "sold",
    address: "440 Ruahine Street, Terrace End",
    suburb: "terrace-end",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-12-04",
    description: [
      "Welcome to 440 Ruahine Street, where 1950s craftsmanship meets future potential. This solid 146m² brick and concrete block home, built in 1957, offers exceptional room to grow and an unbeatable Hokowhitu address—zoned for the city’s most sought-after schools and positioned just moments from scenic river walkways and cycle tracks.",
      "Step into the large entrance foyer, and you’ll immediately sense the scale. The extra-large living area is ideal for family life and entertaining, with plenty of space to relax. The kitchen and dining area may be original, but they’re perfectly placed—overlooking the backyard so you can keep an eye on the kids while planning your dream renovation.",
    ],
    features: [],
    images: [
      "/listings/440-ruahine-street-terrace-end-1.jpg",
    ],
  },
  {
    slug: "23-south-street-west-end",
    title: "PREMIUM OPPORTUNITY in QUALITY LOCATION",
    status: "sold",
    address: "23 South Street, West End",
    suburb: "west-end",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-12-01",
    description: [
      "Step into best of both worlds at 23 South Street, a 111m² character bungalow that blends timeless charm with smart modern upgrades. Positioned just moments from Palmerston North Intermediate Normal School and PNGHS, and an easy walk to the CBD, this is city-fringe living that lets you park the car and upgrade your lifestyle.",
      "Inside, the home showcases ornate ceilings and classic detailing, complemented by a near-new kitchen featuring high-gloss white cabinetry and a modern upgraded bathroom. The light-filled living room with built-in storage creates an inviting space, the home has two heat pumps, ensuring year-round comfort.",
    ],
    features: [],
    images: [
      "/listings/23-south-street-west-end-1.jpg",
    ],
  },
  {
    slug: "36-church-street-awapuni",
    title: "First Home with All the Extras!",
    status: "sold",
    address: "36 Church Street, Awapuni",
    suburb: "awapuni",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-11-25",
    description: [
      "Perfectly positioned at the quiet end of Church St in popular Awapuni.",
      "Step inside and you’re greeted by spacious, sunny open-plan living, dining area with a modernised kitchen, that connects beautifully with the outdoors. New carpet and tiles elevate the interior, while the heat pump and near new DVS system ensure year-round comfort.",
    ],
    features: [],
    images: [
      "/listings/36-church-street-awapuni-1.jpg",
    ],
  },
  {
    slug: "79-worcester-street-ashhurst",
    title: "Affordable, Comfortable, and Ready to Move In!",
    status: "sold",
    address: "79 Worcester Street, Ashhurst",
    suburb: "ashhurst",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-11-23",
    description: [
      "Whether you’re looking to get onto the property ladder or downsize with ease, this well-presented 1995-built, low-maintenance home combines comfort, convenience, and excellent value in a sought-after, friendly community.",
      "On a sunny 513m² section, this three-bedroom home offers light, bright, and inviting open-plan living, complete with a heat pump for year-round comfort. Enjoy the modern, renovated bathroom, and a kitchen with a dishwasher and space for a double-door fridge/freezer. There’s added practicality with a separate laundry and separate toilet.",
    ],
    features: [],
    images: [
      "/listings/79-worcester-street-ashhurst-1.jpg",
    ],
  },
  {
    slug: "16-rosebank-avenue-kelvin-grove",
    title: "Calling Families' - 220m2 House on 800m2 section",
    status: "sold",
    address: "16 Rosebank Avenue, Kelvin Grove",
    suburb: "kelvin-grove",
    beds: 3,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-11-23",
    description: [
      "Set in one of Kelvin Grove’s family-friendly Cul-de-sac’s, this 1992-built 220m² brick and aluminium home delivers space, comfort, and effortless low-maintenance living on a generous family sized 800m² section.",
      "Step inside to a large light-filled living area that flows seamlessly outdoors with 2-sets of ranchsliders to a spacious, family-sized garden – perfect for BBQs, pets, playtime, and summer entertaining. The open-plan dining and kitchen zone anchors the home with plenty of room for busy family life and relaxed gatherings.",
    ],
    features: [],
    images: [
      "/listings/16-rosebank-avenue-kelvin-grove-1.jpg",
    ],
  },
  {
    slug: "3-sutherland-crescent-westbrook",
    title: "Major Price Reduction - Act Fast!",
    status: "sold",
    address: "3 Sutherland Crescent, Westbrook",
    suburb: "palmerston-north",
    beds: 3,
    baths: 1,
    parking: 6,
    priceDisplay: "Sold",
    soldDate: "2025-11-10",
    description: [
      "If you’ve been searching for an affordable first home with room to grow, park, tinker and add value — this is the one you’ve been waiting for.",
      "Set on a generous 821m² fully fenced and gated section, 3 Sutherland Crescent delivers outstanding space both inside and out, with a solid 134m² home, massive drive-through double garage, plus a tandem carport — perfect for extra vehicles, a boat, trailer or camper.",
    ],
    features: [],
    images: [
      "/listings/3-sutherland-crescent-westbrook-1.jpg",
    ],
  },
  {
    slug: "136b-amberley-avenue-highbury",
    title: "130m2 of Low-Maintenance Living!",
    status: "sold",
    address: "136B Amberley Avenue, Highbury",
    suburb: "palmerston-north",
    beds: 2,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-11-09",
    description: [
      "136B Amberley Avenue | Built 1993 | 130m² Home on 392m² Section",
      "Tucked quietly off the road, this well-designed two-bedroom townhouse offers space, comfort, and privacy in one very tidy package. Backing onto the Manawatū Trotting Club racecourse, it enjoys a unique and peaceful outlook.",
    ],
    features: [],
    images: [
      "/listings/136b-amberley-avenue-highbury-1.jpg",
    ],
  },
  {
    slug: "14-antrim-place-hokowhitu",
    title: "Affordable Family Living in Hokowhitu!",
    status: "sold",
    address: "14 Antrim Place, Hokowhitu",
    suburb: "hokowhitu",
    beds: 5,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-10-31",
    description: [
      "Tucked away in a quiet cul-de-sac within top school zones, this 1966-built 158m² home combines space, flexibility, and family-friendly living in sought-after Hokowhitu. With five bedrooms, two bathrooms, and two distinct wings, it’s perfectly designed for growing or multi-generational families.",
      "Generous living zones flow easily throughout, with large picture windows filling the lounge with natural light and French doors leading to a separate dining area — ideal for family meals or relaxed evenings. A heat pump and HRV system keep the home comfortable year-round.",
    ],
    features: [],
    images: [
      "/listings/14-antrim-place-hokowhitu-1.jpg",
    ],
  },
  {
    slug: "37a-stafford-street-shannon",
    title: "Modern. Striking. Yours.",
    status: "sold",
    address: "37A Stafford Street, Shannon",
    suburb: "manawatu",
    beds: 3,
    baths: 2,
    parking: 4,
    priceDisplay: "Sold",
    soldDate: "2025-10-26",
    description: [
      "This near-new (2019 built) three-bedroom, two-bathroom stunner in Shannon is the kind of home that makes an instant impression - sleek, double-glazed and crafted for effortless indoor-outdoor living. Set on a sprawling 868m² section, it’s a rare mix of modern architecture, family function and entertainer’s flair.",
      "Inside, you’ll find a beautifully finished open-plan living area that feels light, generous and perfectly balanced. The designer kitchen takes centre stage - bold black cabinetry, marble-look counters, and an island bench that invites conversation. It’s a space made for cooking, hosting and staying connected.",
    ],
    features: [],
    images: [
      "/listings/37a-stafford-street-shannon-1.jpg",
    ],
  },
  {
    slug: "47-totara-road-awapuni",
    title: "1st Home Buyer & Investor Alert!",
    status: "sold",
    address: "47 Totara Road, Awapuni",
    suburb: "awapuni",
    beds: 3,
    baths: 2,
    parking: 1,
    priceDisplay: "Sold",
    soldDate: "2025-10-19",
    description: [
      "Light-filled, modern, and effortlessly comfortable — this three-bedroom, two-bathroom home offers the perfect mix of style and convenience. Whether you’re upsizing, downsizing, or investing, this Totara Road gem delivers easy living in a great location.",
      "Why you’ll love it:",
    ],
    features: [],
    images: [
      "/listings/47-totara-road-awapuni-1.jpg",
    ],
  },
  {
    slug: "113-stanford-street-north-ashhurst",
    title: "Double Glazed, Renovated & Stylish - Be Quick!",
    status: "sold",
    address: "113 Stanford Street North, Ashhurst",
    suburb: "ashhurst",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-10-13",
    description: [
      "Completely transformed and almost doubled in size, this 139 m² family home delivers the warmth, comfort, and quality of brand-new living. Originally built in 1966 this home has been meticulously extended, relined, and fully insulated to create a modern, light-filled home that’s ready for the next generation.",
      "Every original room has been rebuilt with new linings and insulation, while the extension adds generous open-plan spaces that flow beautifully to the outdoors. The new roof, double-glazed joinery, and freshly painted weatherboard exterior mean there’s nothing left to do but move in and enjoy.",
    ],
    features: [],
    images: [
      "/listings/113-stanford-street-north-ashhurst-1.jpg",
    ],
  },
  {
    slug: "68-seddon-street-takaro",
    title: "4-bedrooms +Sleepout - 2 living - 1428m2 Section!",
    status: "sold",
    address: "68 Seddon Street, Takaro",
    suburb: "palmerston-north",
    beds: 5,
    baths: 3,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-09-29",
    description: [
      "Set on a sprawling 1428m² established section, this versatile 5-bedroom home (including a fully self-contained sleepout) offers the perfect blend of family living, privacy, and lifestyle in a truly beautiful setting.",
      "Step inside and discover a spacious 221m² floor plan designed with family comfort in mind: 4 bedrooms inside, plus a separate double-glazed self-contained sleepout – ideal for extended family, guests, or a work-from-home studio.",
    ],
    features: [],
    images: [
      "/listings/68-seddon-street-takaro-1.jpg",
    ],
  },
  {
    slug: "52-bamfield-street-ashhurst",
    title: "Family Friendly with Extra-Large Garaging!",
    status: "sold",
    address: "52 Bamfield Street, Ashhurst",
    suburb: "ashhurst",
    beds: 4,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-08-20",
    description: [
      "If you’ve been searching for a home that truly ticks all the boxes for family living, this 4-bedroom beauty might just have your name on it. Set on a generous 801m² corner site, just a short stroll to Ashhurst School and Splash Hurst Pool, it’s designed for comfort, connection, and a little bit of everyday magic.",
      "Spacious 144m2 home with two separate living areas mean everyone gets their own space – the kids’ lounge is a game-changer, while the main lounge is light, spacious, and warmed by a heat pump, with French doors opening outside to large decking and garden. The second lounge features a cosy wood burner and heat transfer system for winter warmth.",
    ],
    features: [],
    images: [
      "/listings/52-bamfield-street-ashhurst-1.jpg",
    ],
  },
  {
    slug: "20a-brightwater-terrace-terrace-end",
    title: "Brand-New & Ready to Enjoy – 3-Bedroom",
    status: "sold",
    address: "20A Brightwater Terrace, Terrace End",
    suburb: "terrace-end",
    beds: 3,
    baths: 1,
    parking: 1,
    priceDisplay: "Sold",
    soldDate: "2025-08-15",
    description: [
      "Tucked privately down its own driveway on a landscaped 476m² section, this brand-new 80m² home delivers style, comfort, and low-maintenance living in one of Terrace End’s most connected locations. With three bedrooms, a dual-access bathroom, and everything sparkling new, it’s perfect for first-home buyers, downsizers, or investors seeking a move-in-ready opportunity.",
      "The open-plan kitchen, dining, and living area is bright, inviting, and designed for easy flow to the sunny kwila front deck—ideal for your morning coffee or evening BBQs. The kitchen combines style and practicality, with sleek cabinetry, tiled splashback, quality appliances, and a breakfast bar for casual meals. All three bedrooms feature generous windows and a calming neutral palette, with the master enjoying direct bathroom access. The bathroom offers a modern shower, floating vanity, and warm-toned finishes, while a separate laundry adds everyday convenience.",
    ],
    features: [],
    images: [
      "/listings/20a-brightwater-terrace-terrace-end-1.jpg",
    ],
  },
  {
    slug: "18-mcgregor-street-milson",
    title: "Milson Gem - with extras!",
    status: "sold",
    address: "18 McGregor Street, Milson",
    suburb: "milson",
    beds: 2,
    baths: 1,
    parking: 1,
    priceDisplay: "Sold",
    soldDate: "2025-08-11",
    description: [
      "Tucked behind sleek fencing on a freehold 324m² section, 18 McGregor Street is a hidden delight that blends privacy, polish, and practical comfort. With 82m² of well-designed living space, two double bedrooms, and exceptional presentation throughout, this low-maintenance home is ideal for first-home buyers, downsizers, or savvy investors wanting a move-in ready property in a convenient, city-fringe location.",
      "Step inside to a bright and inviting open-plan living area, where the layout flows effortlessly from lounge/dining into a modern galley-style kitchen. Large windows, a brand new heat pump, DVS system, and Insulmax insulation in the exterior walls ( that's a real plus!), plus ceiling insulation, combine to create a warm, dry, and energy-efficient home – perfect for year-round comfort.",
    ],
    features: [],
    images: [
      "/listings/18-mcgregor-street-milson-1.jpg",
    ],
  },
  {
    slug: "1226-tennent-drive-linton",
    title: "Entry-Level Lifestyle – Linton.",
    status: "sold",
    address: "1226 Tennent Drive, Linton",
    suburb: "manawatu",
    beds: 4,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-08-10",
    description: [
      "If you’ve been dreaming of a lifestyle block but thought it was out of reach — think again. Set on 5,305m² (approx. 1.3 acres) in a sought-after Linton location, this 163m² home offers the best of rural living at an entry-level range.",
      "Divided into three manageable paddocks, the land is ideal for a few sheep, pig, chooks, or your own hobby farm ventures. You’ll also enjoy the practicality of outbuildings and a large lean-to, perfect for storage, a workshop, or shelter for vehicles and gear.",
    ],
    features: [],
    images: [
      "/listings/1226-tennent-drive-linton-1.jpg",
    ],
  },
  {
    slug: "12-14-opie-place-highbury",
    title: "Double the Dwellings – Double the Opportunity",
    status: "sold",
    address: "12-14 Opie Place, Highbury",
    suburb: "palmerston-north",
    beds: 4,
    baths: 2,
    parking: 0,
    priceDisplay: "Sold",
    soldDate: "2025-07-31",
    description: [
      "12-14 Opie Place, Highbury – 1,570m² of Potential-Packed Feehold Land",
      "Calling all visionaries, investors, and hands-on renovators – this is a rare and rewarding find. Set on a generous freehold 1,570m² section in Highbury, this unique offering features two adjoining two-bedroom homes, each with its own kitchen, living, bathroom and laundry.",
    ],
    features: [],
    images: [
      "/listings/12-14-opie-place-highbury-1.jpg",
    ],
  },
  {
    slug: "114-tremaine-avenue-westbrook",
    title: "SOLD Renovator’s Reward – Add Value & Build Equity",
    status: "sold",
    address: "114 Tremaine Avenue, Westbrook",
    suburb: "palmerston-north",
    beds: 3,
    baths: 1,
    parking: 1,
    priceDisplay: "Sold",
    soldDate: "2025-07-31",
    description: [
      "SOLD - 114 Tremaine Avenue, Westbrook – Freehold 685m² Section",
      "Are you ready to roll up your sleeves and get ahead? This solid 1979-built home on a generous 685m² freehold section is packed with potential — and priced to meet the market. Being sold As Is, it’s the perfect chance for first-home buyers, savvy investors, or DIY dynamos to unlock serious value.",
    ],
    features: [],
    images: [
      "/listings/114-tremaine-avenue-westbrook-1.jpg",
    ],
  },
  {
    slug: "38-stillwater-place-westbrook",
    title: "Fire-Damaged Opportunity – Must Be Sold!",
    status: "sold",
    address: "38 Stillwater Place, Westbrook",
    suburb: "palmerston-north",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-07-31",
    description: [
      "Fire-Damaged Opportunity – Selling \"As Is, Where Is\" – Must Be Sold!",
      "38 Stillwater Place, Westbrook – Palmerston North",
    ],
    features: [],
    images: [
      "/listings/38-stillwater-place-westbrook-1.jpg",
    ],
  },
  {
    slug: "28-macdonald-heights-feilding",
    title: "Stylish 3-bedroom + Granny Flat!",
    status: "sold",
    address: "28 Macdonald Heights, Feilding",
    suburb: "feilding",
    beds: 4,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-07-30",
    description: [
      "Welcome to 28 MacDonald Heights – a superbly presented four-bedroom brick home built in 2015, set on a generous corner site in a quiet cul-de-sac surrounded by other quality properties. Designed with low-maintenance living in mind, this home offers the perfect blend of modern comfort, family functionality, and flexibility for extended living.",
      "Step inside to a light-filled, contemporary interior featuring double glazing throughout, two bathrooms (including a duel access bathroom), and spacious open-plan living that flows beautifully to the outdoors – ideal for year-round entertaining and watching the kids play in the sunshine.",
    ],
    features: [],
    images: [
      "/listings/28-macdonald-heights-feilding-1.jpg",
    ],
  },
  {
    slug: "28-monarch-drive-ashhurst",
    title: "Stylish & Serene with Country Views",
    status: "sold",
    address: "28 Monarch Drive, Ashhurst",
    suburb: "ashhurst",
    beds: 3,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-07-04",
    description: [
      "Welcome to 28 Monarch Drive – a stunning 2019-built Fowler Home located at the end of a quiet cul-de-sac in friendly Ashhurst. Surrounded by other quality homes and offering a delightful rural outlook, this 181m² home on a 593m² section is the perfect blend of modern comfort and timeless style.",
      "Step inside to discover an open-plan layout with raked ceiling in the living room and well-placed windows that frame picturesque views of the ranges and wind turbines. The designer kitchen features a huge island bench, modern chattels (including fridge/freezer), and a walk-in pantry, making it a dream for entertainers. The warmth of a woodburner, heat pump, and full double glazing ensures year-round comfort. Seamless indoor-outdoor flow leads to a spacious courtyard, perfect for alfresco living and entertaining.",
    ],
    features: [],
    images: [
      "/listings/28-monarch-drive-ashhurst-1.jpg",
    ],
  },
  {
    slug: "11-cleveland-heights-kelvin-grove",
    title: "Modern Brick Beauty on Cleveland Heights!",
    status: "sold",
    address: "11 Cleveland Heights, Kelvin Grove",
    suburb: "kelvin-grove",
    beds: 3,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-06-29",
    description: [
      "This well-presented brick home offers the ideal blend of comfort, space and style in one of Kelvin Grove’s most desirable pockets. Built in 2010 and beautifully maintained since, it’s a warm and welcoming home with strong street appeal making it ideal as a retirement home or for growing families and empty nesters alike.",
      "Positioned on a 661m² section, this 183m² home offers superb family functionality with two living areas, double glazing, and a well-thought-out layout that caters to modern life.",
    ],
    features: [],
    images: [
      "/listings/11-cleveland-heights-kelvin-grove-1.jpg",
    ],
  },
  {
    slug: "1-strachan-way-highbury",
    title: "AMAZING VALUE! 220m2 Home.",
    status: "sold",
    address: "1 Strachan Way, Highbury",
    suburb: "palmerston-north",
    beds: 4,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-06-19",
    description: [
      "Relocating Owners Say SELL - Immediate Possession Available!",
      "4 Bedrooms | 2 Bathrooms | 2 Living Spaces | 220m² Home | 706m² Section",
    ],
    features: [],
    images: [
      "/listings/1-strachan-way-highbury-1.jpg",
    ],
  },
  {
    slug: "18-truscott-grove-awapuni",
    title: "Spacious, Stylish & Exceptionally Family-Friendly",
    status: "sold",
    address: "18 Truscott Grove, Awapuni",
    suburb: "awapuni",
    beds: 4,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-06-18",
    description: [
      "18 Truscott Grove, Awapuni, Palmerston North",
      "4 Bed | 2 Bath | 2 Living | 230m² Floor Area (approx.)",
    ],
    features: [],
    images: [
      "/listings/18-truscott-grove-awapuni-1.jpg",
    ],
  },
  {
    slug: "24a-rata-street-roslyn",
    title: "Modern, Low-Maintenance & Move-In Ready!",
    status: "sold",
    address: "24A Rata Street, Roslyn",
    suburb: "roslyn",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-06-12",
    description: [
      "24A Rata Street – a smart, stylish and easy-to-maintain low maintenance home perfectly suited for retirees, investors, downsizers or anyone craving comfort without the upkeep.",
      "Tucked away down a peaceful right of way, this 2015-built, three-bedroom property blends modern convenience with effortless living. Solid brick exterior, double-glazed and thoughtfully designed for relaxed everyday life.",
    ],
    features: [],
    images: [
      "/listings/24a-rata-street-roslyn-1.jpg",
    ],
  },
  {
    slug: "90-tane-road-tokomaru",
    title: "Family Lifestyle - 1.41 acres - 4brm + Studio",
    status: "sold",
    address: "90 Tane Road, Tokomaru",
    suburb: "manawatu",
    beds: 5,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-06-09",
    description: [
      "Welcome to 90 Tane Road – the perfect lifestyle property for families wanting space, freedom, and the charm of country living, just 12 minutes (more or less) from Massey and handy to Linton Army Camp.",
      "This beautiful 1935-character bungalow with ornate ceilings sits on a generous 5,725sqm (1.41 acres) section, offering all the room you need for kids to explore, pets to play, and family life to flourish. With four spacious bedrooms and a warm, welcoming feel throughout, there’s plenty of space for everyone to spread out and feel at home.",
    ],
    features: [],
    images: [
      "/listings/90-tane-road-tokomaru-1.jpg",
    ],
  },
  {
    slug: "21-rothesay-place-highbury",
    title: "NEED SPACE? 3 Living • 5 Bed • 2 Bath • 2 Car",
    status: "sold",
    address: "21 Rothesay Place, Highbury",
    suburb: "palmerston-north",
    beds: 5,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-05-23",
    description: [
      "Welcome to this well presented five-bedroom or 4 bed plus office, two-bathroom, brick low maintenance home, offering the ideal blend of space and comfortable family living.",
      "Built in 1999 and thoughtfully designed across a generous 240m² floor plan, this home offers real versatility. Whether you need five bedrooms or four plus a home office, there's room to adapt. With three separate living areas, including a media room that could be used as a sixth bedroom, it's perfectly suited for growing families, multi-generational living, or even hosting boarders to help pay the mortgage.",
    ],
    features: [],
    images: [
      "/listings/21-rothesay-place-highbury-1.jpg",
    ],
  },
  {
    slug: "9-cousins-avenue-east-foxton-beach",
    title: "Sun, Space & Subdivision Potential by the Beach",
    status: "sold",
    address: "9 Cousins Avenue East, Foxton Beach",
    suburb: "manawatu",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-05-19",
    description: [
      "Welcome to 9 Cousins Avenue East, where coastal living meets opportunity in one of Foxton Beach’s best-kept secrets. Set on a whopping 1073m² (more or less) and backing onto tranquil reserve land, this freshly redecorated 3-bedroom home combines lifestyle with long-term upside.",
      "From the moment you step inside, the fresh interior paint and modern décor deliver an inviting coastal vibe. The open-plan kitchen and dining area flows effortlessly to a sun-soaked front deck—perfect for morning coffee or evening BBQs. The separate lounge opens out to this space, enhancing indoor-outdoor living.",
    ],
    features: [],
    images: [
      "/listings/9-cousins-avenue-east-foxton-beach-1.jpg",
    ],
  },
  {
    slug: "224-aranui-road-kairanga",
    title: "1.65 Acre Lifestyle Property in Kairanga",
    status: "sold",
    address: "224 Aranui Road, Kairanga",
    suburb: "manawatu",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-05-13",
    description: [
      "Set in the peaceful countryside of Kairanga, 224 Aranui Road offers the perfect balance of space, comfort, and convenience. Whether you're an animal lover, or simply looking for a little more room to breathe, this 1.65-acre lifestyle property has it all.",
      "Key Features:",
    ],
    features: [],
    images: [
      "/listings/224-aranui-road-kairanga-1.jpg",
    ],
  },
  {
    slug: "5-rosebank-avenue-kelvin-grove",
    title: "Space, Sun & Style in Kelvin Grove!",
    status: "sold",
    address: "5 Rosebank Avenue, Kelvin Grove",
    suburb: "kelvin-grove",
    beds: 4,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-04-20",
    description: [
      "Welcome to 5 Rosebank Ave – Space, Sun & Style in Kelvin Grove! Immediate Procession Available!",
      "An immaculately presented 4-bedroom, 2-bathroom home offering an effortless blend of space, comfort, and low-maintenance living.",
    ],
    features: [],
    images: [
      "/listings/5-rosebank-avenue-kelvin-grove-1.jpg",
    ],
  },
  {
    slug: "16-antrim-place-hokowhitu",
    title: "Great Buying in Hokowhitu!",
    status: "sold",
    address: "16 Antrim  Place, Hokowhitu",
    suburb: "hokowhitu",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-03-23",
    description: [
      "Your opportunity to secure a spacious 165m2 family home in Hokowhitu. If you’ve been searching for a home in a top location with great school zones, modern comforts, and plenty of space for the whole family, this is the one for you!",
      "Nestled at the end of a quiet cul-de-sac, this home offers the perfect combination of peace, privacy, and convenience. The spacious open-plan living area features high ceilings that create a sense of light and space, while seamless indoor-outdoor flow leads to a private courtyard—ideal for summer BBQs and family gatherings.",
    ],
    features: [],
    images: [
      "/listings/16-antrim-place-hokowhitu-1.jpg",
    ],
  },
  {
    slug: "3b-duff-crescent-highbury",
    title: "Near New Home! Double Glazed!",
    status: "sold",
    address: "3B Duff Crescent, Highbury",
    suburb: "palmerston-north",
    beds: 3,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2025-02-05",
    description: [
      "This stylish 3-bedroom property is perfectly positioned to offer both comfort and convenience. It’s ideal for those who appreciate easy-care and near new low maintenance property.",
      "Key Features:",
    ],
    features: [],
    images: [
      "/listings/3b-duff-crescent-highbury-1.jpg",
    ],
  },
  {
    slug: "404-tremaine-avenue-takaro",
    title: "Character, Charm & Modern Comfort!",
    status: "sold",
    address: "404 Tremaine Avenue, Takaro",
    suburb: "palmerston-north",
    beds: 4,
    baths: 1.5,
    parking: 3,
    priceDisplay: "Sold",
    soldDate: "2024-11-28",
    description: [
      "Step into a home that feels like a warm embrace! Bursting with character, charm, and modern comforts, this stunning 176m² bungalow on a generous 912m² section is the perfect blend of old-world elegance and contemporary convenience.",
      "From the moment you arrive, the vibrant red front door welcomes you into a space filled with personality. Gorgeous timber accents, elegant archways, beautiful plaster ceilings and polished hardwood floors set the scene, while the cosy lounge—complete with a charming window seat and ornamental fireplace—invites you to put your feet up and stay awhile. A heat pump ensures comfort in every season.",
    ],
    features: [],
    images: [
      "/listings/404-tremaine-avenue-takaro-1.jpg",
    ],
  },
  {
    slug: "8-pascal-street-city-centre",
    title: "Beautifully Presented - A Must To View!",
    status: "sold",
    address: "8 Pascal Street, City Centre",
    suburb: "palmerston-north",
    beds: 3,
    baths: 2,
    parking: 1,
    priceDisplay: "Sold",
    soldDate: "2024-10-25",
    description: [
      "Discover the perfect blend of character and modern comfort in this charming three-bedroom bungalow.",
      "Lovingly maintained and beautifully presented, this 112sqm home boasts high ceilings with ornate details, a sun-filled enclosed patio that invites you to relax.",
    ],
    features: [],
    images: [
      "/listings/8-pascal-street-city-centre-1.jpg",
    ],
  },
  {
    slug: "9-hewitts-road-linton",
    title: "Upgraded Home with 4 Car Garage!",
    status: "sold",
    address: "9 Hewitts Road, Linton",
    suburb: "manawatu",
    beds: 3,
    baths: 1,
    parking: 4,
    priceDisplay: "Sold",
    soldDate: "2024-10-20",
    description: [
      "This beautifully presented mid-century home offers the perfect blend of charm and modern touches, and it will be ideal for first-time home buyers, growing families, or investors. Set on a spacious 876m2 section with an array of fruit trees, a Walnut tree as well as a large four-car garage, it offers room for family life, pets, and plenty of outdoor fun.",
      "Step inside to find polished wooden floors and a fresh, modern aesthetic. The sleek, upgraded kitchen is a standout, featuring stylish cabinetry and subway tiles. It’s bright and sunny, with everything you need right at your fingertips, making meal preparation a breeze. The living room is equally inviting, with lots of natural light with French doors opening to decking.",
    ],
    features: [],
    images: [
      "/listings/9-hewitts-road-linton-1.jpg",
    ],
  },
  {
    slug: "65-park-road-west-end",
    title: "Priced To Sell! Action Required!!",
    status: "sold",
    address: "65 Park Road, West End",
    suburb: "west-end",
    beds: 2,
    baths: 1,
    parking: 1,
    priceDisplay: "Sold",
    soldDate: "2024-10-20",
    description: [
      "Charming Art Deco Home – Immediate Possession Available!",
      "Act now! The sellers want the Sold sticker on this property! A delightful two-bedroom Art Deco home with immediate possession available, so you can move in and start enjoying this gorgeous property right away. Nestled in a private, well-established setting, this sunny gem offers a rare opportunity for empty nesters, retirees, couples, first-home buyers, and investors alike. With its character-filled charm and unbeatable location near the Esplanade and Lido Aquatic Centre, this is a home you won’t want to miss.",
    ],
    features: [],
    images: [
      "/listings/65-park-road-west-end-1.jpg",
    ],
  },
  {
    slug: "104-fitzroy-street-terrace-end",
    title: "Terrific Family Home in Terrace End",
    status: "sold",
    address: "104 Fitzroy Street, Terrace End",
    suburb: "terrace-end",
    beds: 4,
    baths: 2,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2024-07-16",
    description: [
      "This classic four-bedroom, two-bathroom weatherboard house in the sought-after suburb of Terrace End is a wonderful family-friendly home that is bound to suit a wide range of buyers. It’s a fabulous starter home, or a smart investment and with a big private backyard, there’s plenty of space for the kids to run around and play.",
      "The living area is warm and inviting where you can relax and unwind and soak in some sunshine. A gas heater will keep you warm and cosy in winter.",
    ],
    features: [],
    images: [
      "/listings/104-fitzroy-street-terrace-end-1.jpg",
    ],
  },
  {
    slug: "66-salisbury-street-ashhurst",
    title: "Affordable  First Home - Freehold Title!",
    status: "sold",
    address: "66 Salisbury Street, Ashhurst",
    suburb: "ashhurst",
    beds: 1,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2024-06-16",
    description: [
      "This cute and chic 1 bedroom home situated in the lovely community of Ashhurst is a fantastic opportunity to get on the property ladder, ideal for first home buyers, couples or a young family. It’s been beautifully updated, just move in and enjoy all this delightful home has to offer!",
      "The cosy living area has lots of natural light and is great place to relax and unwind with loved ones. It connects nicely to the kitchen and dining area which flows out to a large, covered deck area. It’s a wonderful space for entertaining family and friends and you can dine al fresco all year round.",
    ],
    features: [],
    images: [
      "/listings/66-salisbury-street-ashhurst-1.jpg",
    ],
  },
  {
    slug: "39-gloucester-street-takaro",
    title: "REAP THE REWARDS",
    status: "sold",
    address: "39 Gloucester Street, Takaro",
    suburb: "palmerston-north",
    beds: 3,
    baths: 1,
    parking: 2,
    priceDisplay: "Sold",
    soldDate: "2024-06-02",
    description: [
      "Discover the hidden potential of this unique property! Sitting on a generous 985m² section, this sunny 3-bedroom, 113m² home is brimming with possibilities for those ready to roll up their sleeves and transform it into a dream residence or a lucrative investment..",
      "Key Features.",
    ],
    features: [],
    images: [
      "/listings/39-gloucester-street-takaro-1.jpg",
    ],
  },
  {
    slug: "138a-amberley-avenue-highbury",
    title: "Low Maintenance - Freehold Townhouse",
    status: "sold",
    address: "138A Amberley Avenue, Highbury",
    suburb: "palmerston-north",
    beds: 2,
    baths: 1,
    parking: 1,
    priceDisplay: "Sold",
    soldDate: "2024-05-13",
    description: [
      "This neat and tidy single level 2 bedroom brick unit is tucked away off the road on an easy care section with well thought out landscaping and just the right amount of space. Perfect for couples, empty nesters, first home buyers and investors, it’s a delightful home with real appeal...",
      "Light and sunny with a beautiful use of colour it feels warm and welcoming with real heart. The open plan living room is cosy and inviting with big windows to let in lots of natural light and easy access outside. It opens out to a covered private deck where you can soak up the sun in a lovely garden setting.",
    ],
    features: [],
    images: [
      "/listings/138a-amberley-avenue-highbury-1.jpg",
    ],
  },
];
